version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/GraphSample" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
